### ISSUE TITLE
chunk size designation

### ISSUE THREAD

**Issue by stevenlehrer** [USC-IGC/ukbb_parser#3]
How can I add a chunk size designation to this command

ukbb_parser inventory --incsv ukbb_spreadsheet.csv --outcsv jobs_inventory.csv --datatype careers --level 3 --code 6113 --level 4 --code 1151010 --all_codes

**Comment by ahzhu** [comment]
A "--chunksize" flag has been added. The default is 1000.

**Comment by stevenlehrer** [comment]
No such flag

D:\>ukbb_parser inventory --incsv ukb43365.csv --outcsv jobs_inventory.csv --datatype careers --level 3 --code 6113 --chunksize 1000
Usage: ukbb_parser inventory [OPTIONS]
Try 'ukbb_parser inventory --help' for help.

Error: no such option: --chunksize

________________________________

**Comment by stevenlehrer** [comment]
Also, the default is still 3582, which is far too big for a win10 pc with 64 gb ram

D:\>ukbb_parser inventory --incsv ukb43365.csv --outcsv jobs_inventory.csv --datatype careers --level 3 --code 6113
Currently checking for the required datafields
Caution: Datafield 132 is not included in your data.
Number of Columns: 16747
Chunk size: 3582

________________________________

**Comment by stevenlehrer** [comment]
Sorry, I had to reload the program, now it seems to be working ok. Many thanks
sl

________________________________
